### ISSUE TITLE
has leaked IntentReceiver

### ISSUE THREAD

**Issue by jeffreyliu8** [plaid/link#200]
when closing a sample project, get error where it says there is a leaked intentReceiver on google pixel android Oreo 8.0. By closing I mean just click the little cross on top right.

09-07 16:16:00.400 31582-31582/com.test E/ActivityThread: Activity banking.plaid.PlaidActivity has leaked IntentReceiver org.chromium.content.browser.accessibility.LollipopBrowserAccessibilityManager$1@dbdf53b that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                android.app.IntentReceiverLeaked: Activity com.qvivr.hoot.banking.plaid.PlaidActivity has leaked IntentReceiver org.chromium.content.browser.accessibility.LollipopBrowserAccessibilityManager$1@dbdf53b that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                    at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1333)
                                                                    at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1114)
                                                                    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1405)
                                                                    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1378)
                                                                    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1366)
                                                                    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:603)
                                                                    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:603)
                                                                    at org.chromium.content.browser.accessibility.LollipopBrowserAccessibilityManager.<init>(LollipopBrowserAccessibilityManager.java:3)
                                                                    at org.chromium.content.browser.accessibility.BrowserAccessibilityManager.create(BrowserAccessibilityManager.java:1)
                                                                    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by michaelckelly** [comment]
@jeffreyliu8 - Can you please share the code you're using to integrate Link, specifically the Link initialization snippet and your URL handler? That will help to diagnose this issue.
